### ISSUE TITLE
Docker Build Error

### ISSUE THREAD

**Issue by sjakati98** [danielschemmel/klee-z3float-aachen#2]
When trying to use the docker image, as indicated [here](https://srg.doc.ic.ac.uk/projects/klee-float/getting-started.html), I receive the error:

```
$ sudo ./scripts/docker_aachen_build.sh 
+ set -e
+ EXPECTED_COMSYS_IMG_SHA256=sha256:c83f50ae1271b17b1eeb27a0e3ebf4f659bfdb96134d35358df0355e3ce26d2f
+ BASE_IMG=comsys/klee-dev-fpbench-prebuilt:latest
+ docker inspect --format ok comsys/klee-dev-fpbench-prebuilt:latest

Error: No such object: comsys/klee-dev-fpbench-prebuilt:latest
```

(I am currently on Ubuntu 16.04.3 LTS if that would be a factor.)

**Comment by danielschemmel** [comment]
Did you do the `docker pull comsys/klee-dev-fpbench-prebuilt:latest`?
If so, please post the output of `docker images` on the machine you are using, so I can maybe see what is going wrong.

**Comment by sjakati98** [comment]
This is the output from ``docker images``:
```
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
hello-world         latest              e38bc07ac18e        6 weeks ago         1.85kB
klee/klee           latest              36dc2d4c1fe0        6 weeks ago         1.26GB

```

UPDATE: Wow, ok I see the problem. I never pulled the klee-float image.
